# Generated by Django 3.1 on 2020-09-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('summary', models.TextField(null=True)),
                ('article_url', models.CharField(max_length=1000, null=True)),
                ('image_url', models.CharField(max_length=1000, null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
